package parser;

public enum TokenType {
    END,
    OP_PLUS,
    OP_MINUS,
    OP_MODULO,
    OP_MULTIPLY,
    OP_DIV,
    OPEN_ROUND_BRACKET,
    CLOSE_ROUND_BRACKET,
    OPEN_SQUARE_BRACKET,
    CLOSE_SQUARE_BRACKET,
    NUMBER,
    VAR_NAME,
    EQUALS,
    NOT_EQUALS,
    LESS,
    GREATER,
    LESS_OR_EQUAL,
    GREATER_OR_EQUAL
}
